# Generated by Django 5.2.4 on 2025-10-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_usercertificate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usercertificate',
            new_name='progress_us_user_id_cd88c3_idx',
            old_name='progress_use_user_id_2a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='usercertificate',
            new_name='progress_us_program_0ba0df_idx',
            old_name='progress_use_program_2a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='usercertificate',
            new_name='progress_us_certifi_8151f4_idx',
            old_name='progress_use_certifi_2a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='usercertificate',
            new_name='progress_us_is_acti_3e20e1_idx',
            old_name='progress_use_is_acti_2a8b8a_idx',
        ),
    ]
