# Generated by Django 5.2.4 on 2025-10-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_rename_progress_use_user_id_2a8b8a_idx_progress_us_user_id_cd88c3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgedefinition',
            name='badge_type',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Prata'), ('GOLD', 'Ouro'), ('PLATINUM', 'Platina')], max_length=10),
        ),
        migrations.AlterField(
            model_name='badgedefinition',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Médio'), ('HARD', 'Difícil'), ('CERTIFICATE', 'Certificado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='certificatetest',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='challengecompletion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Médio'), ('HARD', 'Difícil'), ('CERTIFICATE', 'Certificado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='challenge_completion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_earned', to='progress.challengecompletion'),
        ),
    ]
